const { jsPDF } = require('jspdf');
require('jspdf-autotable');

const generateInvoicePDF = (order, type) => {
    const doc = new jsPDF();

    doc.text(`${type} Invoice`, 14, 20);
    doc.setFontSize(10);
    doc.text(`Order ID: ${order._id}`, 14, 30);
    doc.text(`Date: ${new Date(order.createdAt).toLocaleDateString()}`, 14, 36);

    const tableData = order.products.map(item => [
        item.product.name,
        item.quantity,
        item.sellingPrice || item.costPrice,
        (item.quantity * (item.sellingPrice || item.costPrice)).toFixed(2)
    ]);

    doc.autoTable({
        startY: 45,
        head: [['Product', 'Quantity', 'Price', 'Total']],
        body: tableData,
    });

    doc.text(`Total Amount: ₹${order.totalAmount}`, 14, doc.autoTable.previous.finalY + 10);

    return doc.output('arraybuffer'); // Return buffer to send as response
};

const generateSalesReportPDF = ({ orders, stats, chartData, generatedBy, dateRange }) => {
    const doc = new jsPDF({ orientation: 'landscape' });
    const generatedAt = new Date();

    doc.setFontSize(18);
    doc.text('Sales Report', 14, 18);

    doc.setFontSize(10);
    doc.text(`Generated By: ${generatedBy?.name || 'Unknown User'} (${generatedBy?.role || 'N/A'})`, 14, 28);
    doc.text(`Generated At: ${generatedAt.toLocaleString()}`, 14, 34);
    doc.text(`Period: ${dateRange.startDate.toLocaleDateString()} - ${dateRange.endDate.toLocaleDateString()}`, 14, 40);

    doc.autoTable({
        startY: 50,
        head: [['Metric', 'Value']],
        body: [
            ['Completed Sales', `INR ${Number(stats.sales || 0).toLocaleString()}`],
            ['Pending Sales', `INR ${Number(stats.pendingSales || 0).toLocaleString()}`],
            ['Total Orders', String(stats.totalOrders || 0)],
            ['Completed Orders', String(stats.completedOrders || 0)],
            ['Pending Orders', String(stats.pendingOrders || 0)],
            ['Cancelled Orders', String(stats.cancelledOrders || 0)]
        ],
        styles: { fontSize: 9 },
        headStyles: { fillColor: [59, 130, 246] }
    });

    const dailyRows = chartData.map(item => [
        item._id,
        `INR ${Number(item.amount || 0).toLocaleString()}`,
        `INR ${Number(item.pendingAmount || 0).toLocaleString()}`
    ]);

    doc.autoTable({
        startY: doc.lastAutoTable.finalY + 12,
        head: [['Date', 'Completed Sales', 'Pending Sales']],
        body: dailyRows.length ? dailyRows : [['No data', 'INR 0', 'INR 0']],
        styles: { fontSize: 9 },
        headStyles: { fillColor: [16, 185, 129] }
    });

    const orderRows = orders.map(order => [
        order._id.toString(),
        order.customerName,
        order.status,
        new Date(order.createdAt).toLocaleDateString(),
        `INR ${Number(order.totalAmount || 0).toLocaleString()}`
    ]);

    doc.autoTable({
        startY: doc.lastAutoTable.finalY + 12,
        head: [['Order ID', 'Customer', 'Status', 'Date', 'Amount']],
        body: orderRows.length ? orderRows : [['No orders found', '-', '-', '-', 'INR 0']],
        styles: { cellPadding: 1.5, fontSize: 8, overflow: 'linebreak' },
        headStyles: { fillColor: [31, 41, 55] }
    });

    return doc.output('arraybuffer');
};

const generateProductSalesReportPDF = ({ productSales, generatedBy }) => {
    const doc = new jsPDF({ orientation: 'landscape' });
    const generatedAt = new Date();

    doc.setFontSize(18);
    doc.text('Product Sales Report', 14, 18);

    doc.setFontSize(10);
    doc.text(`Generated By: ${generatedBy?.name || 'Unknown User'} (${generatedBy?.role || 'N/A'})`, 14, 28);
    doc.text(`Generated At: ${generatedAt.toLocaleString()}`, 14, 34);

    const tableRows = productSales.map(item => [
        item.productName,
        String(item.totalQuantity),
        String(item.completedQuantity),
        String(item.pendingQuantity),
        String(item.cancelledQuantity),
        `INR ${Number(item.completedRevenue || 0).toLocaleString()}`
    ]);

    doc.autoTable({
        startY: 45,
        head: [['Product', 'Total Ordered', 'Completed Sold', 'Pending', 'Cancelled', 'Completed Revenue']],
        body: tableRows.length ? tableRows : [['No products sold', '0', '0', '0', '0', 'INR 0']],
        styles: { cellPadding: 2, fontSize: 9, overflow: 'linebreak' },
        headStyles: { fillColor: [22, 163, 74] }
    });

    return doc.output('arraybuffer');
};

const generateFilteredOrdersPDF = ({ title, orders, type, generatedBy, filters }) => {
    const doc = new jsPDF({ orientation: 'landscape' });
    const generatedAt = new Date();
    const isSales = type === 'sales';
    const selectedProductId = filters?.productId || '';
    const getReportItems = (order) => {
        if (!selectedProductId) return order.products;
        return order.products.filter(item => {
            const itemProductId = item.product?._id?.toString() || item.product?.toString();
            return itemProductId === selectedProductId;
        });
    };

    doc.setFontSize(18);
    doc.text(title, 14, 18);

    doc.setFontSize(10);
    doc.text(`Generated By: ${generatedBy?.name || 'Unknown User'} (${generatedBy?.role || 'N/A'})`, 14, 28);
    doc.text(`Generated At: ${generatedAt.toLocaleString()}`, 14, 34);

    const filterSummary = [
        filters?.keyword ? `Keyword: ${filters.keyword}` : null,
        filters?.date ? `Date: ${filters.date}` : null,
        filters?.productName ? `Product: ${filters.productName}` : null
    ].filter(Boolean).join(' | ') || 'All records';
    doc.text(`Filters: ${filterSummary}`, 14, 40);

    const totalAmount = orders.reduce((sum, order) => {
        return sum + getReportItems(order).reduce((itemSum, item) => {
            const unitPrice = Number(isSales ? item.sellingPrice : item.costPrice) || 0;
            return itemSum + (Number(item.quantity || 0) * unitPrice);
        }, 0);
    }, 0);
    const totalQuantity = orders.reduce((sum, order) => {
        return sum + getReportItems(order).reduce((itemSum, item) => itemSum + Number(item.quantity || 0), 0);
    }, 0);

    doc.autoTable({
        startY: 48,
        head: [['Metric', 'Value']],
        body: [
            ['Total Orders', String(orders.length)],
            ['Total Quantity', String(totalQuantity)],
            ['Total Amount', `INR ${totalAmount.toLocaleString()}`]
        ],
        styles: { fontSize: 9 },
        headStyles: { fillColor: [59, 130, 246] }
    });

    const tableRows = orders.flatMap(order => {
        const partyName = isSales ? order.customerName : order.supplier?.name || 'Unknown Supplier';
        return getReportItems(order).map(item => {
            const unitPrice = Number(isSales ? item.sellingPrice : item.costPrice) || 0;
            const quantity = Number(item.quantity) || 0;

            return [
                order._id.toString(),
                new Date(order.createdAt).toLocaleDateString(),
                partyName,
                item.product?.name || 'Unknown Product',
                String(quantity),
                `INR ${unitPrice.toLocaleString()}`,
                `INR ${(quantity * unitPrice).toLocaleString()}`,
                order.status
            ];
        });
    });

    doc.autoTable({
        startY: doc.lastAutoTable.finalY + 12,
        head: [[
            'Order ID',
            'Date',
            isSales ? 'Customer' : 'Supplier',
            'Product',
            'Qty',
            'Unit Price',
            'Line Total',
            'Status'
        ]],
        body: tableRows.length ? tableRows : [['No orders found', '-', '-', '-', '0', 'INR 0', 'INR 0', '-']],
        styles: { cellPadding: 1.5, fontSize: 8, overflow: 'linebreak' },
        headStyles: { fillColor: [31, 41, 55] },
        columnStyles: {
            0: { cellWidth: 48 },
            3: { cellWidth: 42 }
        }
    });

    return doc.output('arraybuffer');
};

module.exports = { generateInvoicePDF, generateSalesReportPDF, generateProductSalesReportPDF, generateFilteredOrdersPDF };
